name: Your Workflow Name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vega_job: # Remove the space and use an underscore
    runs-on: ubuntu-latest
    steps:
      - name: ant-build
        run: echo "package"
        shell: bash

